name: Update Trending JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC)
env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay requests python-dotenv

      - name: Run Python Script
        run: python -u script.py

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add trending.json
          git commit -m "Update Trending CVE"
          git push
